services:
  akari-db:
    image: postgres:18.1@sha256:5ec39c188013123927f30a006987c6b0e20f3ef2b54b140dfa96dac6844d883f
    container_name: akari-db
    env_file: .env
    volumes:
      - db-store:/var/lib/pgsql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      TZ: UTC
  akari-db-side:
    image: alpine:3.22@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412
    container_name: akari-db-side
    command: ["sh", "-c", "echo 'Wake up db-side'"]
    depends_on:
      akari-db:
        condition: service_healthy

volumes:
  db-store:
