services:
  akari-db:
    image: postgres:17.6@sha256:00bc86618629af00d2937fdc5a5d63db3ff8450acf52f0636ec813c7f4902929
    container_name: akari-db
    env_file: .env
    volumes:
      - db-store:/var/lib/pgsql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      TZ: UTC
  akari-db-side:
    image: alpine:3.21@sha256:5405e8f36ce1878720f71217d664aa3dea32e5e5df11acbf07fc78ef5661465b
    container_name: akari-db-side
    command: ["sh", "-c", "echo 'Wake up db-side'"]
    depends_on:
      akari-db:
        condition: service_healthy

volumes:
  db-store:
