apiVersion: v1
kind: ConfigMap
metadata:
  name: akari-config
  namespace: akari
  labels:
    app.kubernetes.io/name: akari
    app.kubernetes.io/component: bot
    app.kubernetes.io/part-of: akari
data:
  AKARI_ENV: production
  LOG_LEVEL: info
  LOG_FORMAT: json
  DISCORD_BOT_NAME_REG_EXP: "^akari"
  POSTGRES_HOST: akari-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: akari
  POSTGRES_NAME: akari
  POSTGRES_SSLMODE: disable
