apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akari
commonLabels:
  app.kubernetes.io/name: akari
  app.kubernetes.io/part-of: akari
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - postgres.yaml
  - nocodb-secret.yaml
  - nocodb-pvc.yaml
  - nocodb.yaml
images:
  - name: ghcr.io/kizuna-org/akari
    newTag: v0.1.1
