apiVersion: v1
kind: Secret
metadata:
  name: nocodb-secrets
  namespace: akari
  labels:
    app.kubernetes.io/name: nocodb
    app.kubernetes.io/component: nocodb
    app.kubernetes.io/part-of: akari
type: Opaque
stringData:
  NC_DB: pg://akari-postgres:5432?u=akari&p=changeme&d=akari
  NC_AUTH_JWT_SECRET: changeme

