apiVersion: v1
kind: Secret
metadata:
  name: akari-secrets
  namespace: akari
  labels:
    app.kubernetes.io/name: akari
    app.kubernetes.io/component: bot
    app.kubernetes.io/part-of: akari
type: Opaque
stringData:
  POSTGRES_PASSWORD: changeme
  DISCORD_TOKEN: changeme
  LLM_PROJECT_ID: ""
  LLM_LOCATION: ""
  LLM_MODEL_NAME: ""
